version: '3.7'
services:
  admin_merchant:
    image: $REGISTRY_URL/$PROJECT_NAME:test
    environment:
      - "APP_PROJECT=admin_merchant"
      - "APP_ENV=test"
    ports:
      - 8003:3000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
    networks:
      - default-network
networks:
  default-network:
    external: true
